/*
# Chat attachments storage bucket (no Supabase Auth)

1. Storage
- Creates a private bucket `chat-attachments` for files uploaded from the chat.
- The app uses custom session auth (not Supabase Auth), so auth.uid() is null
  for the browser. We allow anon uploads to the bucket (the path includes a
  random UUID so it's not guessable) and the edge function validates the
  session token before processing the file.

2. Policies
- INSERT: anon + authenticated can upload to `chat-attachments`. The path
  includes a random UUID generated by the browser, making it hard to guess.
- SELECT/DELETE: no policy for anon/authenticated = denied by default.
  Only the service role (edge function) can read and delete files.

3. Notes
- The bucket is PRIVATE. Files are never exposed to the browser.
- The edge function uses SERVICE_ROLE_KEY to fetch and delete uploaded files.
- After the edge function downloads the file, it deletes it from Storage.
*/

INSERT INTO storage.buckets (id, name, public)
VALUES ('chat-attachments', 'chat-attachments', false)
ON CONFLICT (id) DO NOTHING;

-- Allow anon uploads (the app has custom auth, not Supabase Auth)
DROP POLICY IF EXISTS "anon_upload_attachments" ON storage.objects;
CREATE POLICY "anon_upload_attachments"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'chat-attachments');